# Generated by Django 5.2.15 on 2026-06-19 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 19, 17, 27, 27, 612716, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
