# Generated by Django 5.2.15 on 2026-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
